### ISSUE TITLE
autonomousduck.com is inaccessible

### ISSUE THREAD

**Issue by joaobrasil65** [krumiaa/MindMaker#1]

**Comment by krumiaa** [comment]
Maybe server was temporarily down. Just tried http://www.autonomousduck.com/ and its working. Let me know if you have any trouble reaching it again

**Comment by joaobrasil65** [comment]
I'm getting a Forbidden Error 403

**Comment by krumiaa** [comment]
I suspect this was due to the security settings on your web browser, I didnt have SSL enabled for the domain yet(just got around to it today). If you try now, I believe it should work. Make sure to include https:// if your typing it in manually

**Comment by joaobrasil65** [comment]
It works!
