### ISSUE TITLE
Training the agent is not working

### ISSUE THREAD

**Issue by james-yoo** [krumiaa/MindMaker#10]
Hi,

I am testing MindMaker example project with UE5.
I would like to know that default setting(e.g. PPO2, number of training episode, ..) of this example project is enough to train the cart pole RL agent? I have tried training about over 30 times but never succeeded.

**Comment by krumiaa** [comment]
In UE5 some of the game engine physics and object dynamics were changed, so the example projects may not give the same results as they did in UE4, specifically the cart pole example which is sensitive to object dynamics. This is why the UE5 version of mindmaker is still a beta release. The basic functionality is there but the examples haven't been fully adapted to give identical results. You will likely have to tweak some of the physics values, gravity etc. to get cart pole working as it did in UE4.

If you need more hands assistance, I do consulting work on machine learning and game AI. you can reach out to me at aaron.krumins@gmail.com

**Comment by james-yoo** [comment]
@krumiaa,
Thank you for your quick response and close the issue.

**Comment by james-yoo** [comment]
@krumiaa,
I have sent the email regarding of the tuning parameters.
