### ISSUE TITLE
Tensorboard logs do not generate

### ISSUE THREAD

**Issue by jusbw06** [krumiaa/MindMaker#3]
Hi, I bought and modified the MindMaker Single Node Project. I am trying to output the training statistics to tensorboard. However, regardless of my input to the tensorboard_log parameter, no files are generated. Would you have any ideas as to why?

Thank you.

![image](https://user-images.githubusercontent.com/20483208/120941619-697d7f80-c6d8-11eb-9038-b605a4354abe.png)

**Comment by krumiaa** [comment]
I will take a peak at this and get back to you.
