### ISSUE TITLE
Do Mindmakers RL Algorithms support float Inputs?

### ISSUE THREAD

**Issue by FLOROID** [krumiaa/MindMaker#8]
Hello there,

I'm currently working on a project for my bachelors paper and
want to train an AI agent using MindMaker.
When looking at the example project I noticed that in the "Make Observations" function 
two Integer values are turned into strings appended in a [Integer, Integer] structure and passed into MindMaker.
Could I also pass float values to MindMaker here or are these values supposed to be either 0 or 1?

Thanks in advance.

**Comment by krumiaa** [comment]
Yes, you can definitely use floats for observations, wouldn’t be much fun if you couldn’t ;-) A DRL cart pole example where this is explicitly the case is included with the Mindmaker DRL project files which you can download from UE marketplace. https://unrealengine.com/marketplace/en-US/product/neurostudio-self-learning-ai

Importantly you will want to make sure you define that you are using floats in the observation space shape of the launch mindmaker blueprint function, you can also see this in some of the screenshots for the tutorial for that cart pole example. https://towardsdatascience.com/create-a-custom-deep-reinforcement-learning-environment-in-ue4-cf7055aebb3e

Hope this helps

**Comment by FLOROID** [comment]
Ah, perfect! Yes I found the screenshot you're referencing :D
Thank you, that helps me out a lot! 😊
